name: Build and Push Docker Image to Docker Hub with Incremental Tag

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the latest Docker tag
        id: get_version
        run: |
          # Fetch the latest Docker tag from Docker Hub
          latest_tag=$(docker pull ${{ secrets.DOCKER_ORG }}/my-web-app:latest || echo "v0")  # Defaults to v0 if no image exists
          
          # Extract the version number and increment it
          VERSION_NUM=$(echo $latest_tag | sed 's/v//')  # Remove "v" prefix
          NEXT_VERSION="v$((VERSION_NUM + 1))"  # Increment the version number

          echo "VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "Next version: $NEXT_VERSION"

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_ORG }}/my-web-app:${{ env.VERSION }} .

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_ORG }}/my-web-app:${{ env.VERSION }}
